# @file
# .travis.yml - PKP Plugins Integration

language: php

dist: bionic
os: linux
language: php

addons:
  postgresql: "9.5"
  apt:
    update: true

php:
  - 7.4
  - 8.0
env:
  - APPLICATION=ojs BRANCH=stable-3_3_0 TEST=mysql
  - APPLICATION=ojs BRANCH=stable-3_3_0 TEST=pgsql
  - APPLICATION=omp BRANCH=stable-3_3_0 TEST=mysql
  - APPLICATION=omp BRANCH=stable-3_3_0 TEST=pgsql
  - APPLICATION=ops BRANCH=stable-3_3_0 TEST=mysql
  - APPLICATION=ops BRANCH=stable-3_3_0 TEST=pgsql

install:
  # Prepare OJS/OMP environment
  - git clone -b ${BRANCH} https://github.com/pkp/${APPLICATION} ~/${APPLICATION}
  - cd ~/${APPLICATION}
  - git submodule update --init --recursive
  - source lib/pkp/tools/travis/prepare-tests.sh
  - lib/pkp/tools/travis/prepare-webserver.sh
  # Build/install dependencies
  - lib/pkp/tools/travis/install-composer-dependencies.sh
  - npm i g -npm && npm install && npm run build
  # Make sure we're using the current checkout of this repo rather than the built-in OJS/OMP version
  - ln -s ${TRAVIS_BUILD_DIR} ~/${APPLICATION}/plugins/generic/customHeader
  # Install OJS/OMP & prep data environment
script:
  - $(npm bin)/cypress run --spec "cypress/tests/data/10-Installation.spec.js,cypress/tests/data/20-CreateContext.spec.js"
  - $(npm bin)/cypress run --config integrationFolder=plugins/generic/customHeader/cypress/tests
after_failure:
  - cat error.log
